### ISSUE TITLE
Zotra for Windows

### ISSUE THREAD

**Issue by Ypot** [mpedramfar/zotra#11]
Hi
I love this idea, but I am using Windows.
Is there a way to use zotra in Windows?
I can't see clearly what of the 3 methods I could use, I am afraid no one.

**Comment by mpedramfar** [comment]
Hi,
I don't personally use Windows but it's not immediately clear to me why it should fail.
Is there an issue when you try to install `zotra-cli`?

**Comment by Ypot** [comment]
Hi!

I thought I couldn't install zotra-cli!!

Note: 
 _nodejs.exe_ is in the PATH, of the environment variables: C:\Program Files\nodejs\
And in the init.el exec-path C:\Program Files\nodejs.

Now I get this error message
```
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- C:\Users\user\zotra-cli\bin\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\user\zotra-cli\bin\index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\user\\zotra-cli\\bin\\index.js' ]
}

Node.js v18.17.1

zotra-get-json: End of file while parsing JSON: "unexpected token near end of file", "<string>", 1, 0, 0
<left-fringe> <drag-mouse-1> is undefined
```

**Comment by mpedramfar** [comment]
I see. Can you run `zotra --help` or `node /path/to/index.js --help` from a shell like described in the README of `zotra-cli`?
What's the output of that?

**Comment by Ypot** [comment]
Hi, similar output:

```
C:\Users\user>zotra --help
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- C:\Users\user\zotra-cli\bin\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (C:\Users\user\zotra-cli\bin\index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\user\\zotra-cli\\bin\\index.js' ]
}

Node.js v18.17.1
```

**Comment by mpedramfar** [comment]
If I just clone `zotra-cli` and not install it and then try to run it, I get the same error!
Have you installed it following the instruction in README? Were there any errors?

**Comment by Ludiko** [comment]
I had errors when installing the  "Install Additional Tools for Node.js".

But I don't remember any error installing zotra-cli. I repeated the steps, anyway:

```org
* git clone --recurse-submodules https://github.com/mpedramfar/zotra-cli.git

C:\Users\user>git clone --recurse-submodules https://github.com/mpedramfar/zotra-cli.git

Cloning into 'zotra-cli'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 43 (delta 15), reused 29 (delta 8), pack-reused 0
Receiving objects: 100% (43/43), 101.78 KiB | 1011.00 KiB/s, done.
Resolving deltas: 100% (15/15), done.
Submodule 'module/translation-server' (https://github.com/zotero/translation-server.git) registered for path 'module/translation-server'
Cloning into '/c/Users/user/zotra-cli/module/translation-server'...
remote: Enumerating objects: 1111, done.
remote: Counting objects: 100% (480/480), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 1111 (delta 396), reused 399 (delta 346), pack-reused 631
Receiving objects: 100% (1111/1111), 741.26 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (694/694), done.
Submodule path 'module/translation-server': checked out '03290315ad76a06bcb5a993047172a0f90815175'
Submodule 'modules/translate' (https://github.com/zotero/translate.git) registered for path 'module/translation-server/modules/translate'
Submodule 'modules/translators' (https://github.com/zotero/translators) registered for path 'module/translation-server/modules/translators'
Submodule 'modules/utilities' (https://github.com/zotero/utilities.git) registered for path 'module/translation-server/modules/utilities'
Submodule 'modules/zotero-schema' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/zotero-schema'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate'...
remote: Enumerating objects: 260, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 260 (delta 47), reused 38 (delta 32), pack-reused 192
Receiving objects: 100% (260/260), 172.70 KiB | 309.00 KiB/s, done.
Resolving deltas: 100% (140/140), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translators'...
remote: Enumerating objects: 20716, done.
remote: Counting objects: 100% (2162/2162), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 20716 (delta 1974), reused 2005 (delta 1909), pack-reused 18554
Receiving objects: 100% (20716/20716), 15.85 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (12457/12457), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/utilities'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 253 (delta 65), reused 73 (delta 50), pack-reused 147
Receiving objects: 100% (253/253), 378.73 KiB | 3.26 MiB/s, done.
Resolving deltas: 100% (126/126), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/zotero-schema'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 2.38 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/translate': checked out '6a9270c992e39998389267810ec21b8cd735730e'
Submodule 'modules/utilities' (https://github.com/zotero/utilities.git) registered for path 'module/translation-server/modules/translate/modules/utilities'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate/modules/utilities'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 253 (delta 65), reused 73 (delta 50), pack-reused 147
Receiving objects: 100% (253/253), 378.73 KiB | 392.00 KiB/s, done.
Resolving deltas: 100% (126/126), done.
Submodule path 'module/translation-server/modules/translate/modules/utilities': checked out 'c173fe4e73f908da917fe7a5dab05ae94d423d6d'
Submodule 'resource/schema/global' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/translate/modules/utilities/resource/schema/global'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate/modules/utilities/resource/schema/global'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 3.04 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/translate/modules/utilities/resource/schema/global': checked out '634ba4f99bfd06f4b5b8c88879ff65e2dfd410b3'
Submodule path 'module/translation-server/modules/translators': checked out '8c9da9b034a851c2d22e15aa3c31206d1f2b0f06'
Submodule path 'module/translation-server/modules/utilities': checked out '3143d5518d0044152bdca2b11e5ba2de92b5101f'
Submodule 'resource/schema/global' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/utilities/resource/schema/global'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/utilities/resource/schema/global'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 3.46 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/utilities/resource/schema/global': checked out '634ba4f99bfd06f4b5b8c88879ff65e2dfd410b3'
Submodule path 'module/translation-server/modules/zotero-schema': checked out 'c9f6c78a3d8199de62496c8dc7c188e74ac22341'


C:\Users\user>cd zotra-cli

C:\Users\user\zotra-cli>npm install -g .

up to date in 885ms

C:\Users\user\zotra-cli>
```

**Comment by Ypot** [comment]
I had errors when installing the  "Install Additional Tools for Node.js".

But I don't remember any error installing zotra-cli. I repeated the steps, anyway:

```org

C:\Users\user>git clone --recurse-submodules https://github.com/mpedramfar/zotra-cli.git

Cloning into 'zotra-cli'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 43 (delta 15), reused 29 (delta 8), pack-reused 0
Receiving objects: 100% (43/43), 101.78 KiB | 1011.00 KiB/s, done.
Resolving deltas: 100% (15/15), done.
Submodule 'module/translation-server' (https://github.com/zotero/translation-server.git) registered for path 'module/translation-server'
Cloning into '/c/Users/user/zotra-cli/module/translation-server'...
remote: Enumerating objects: 1111, done.
remote: Counting objects: 100% (480/480), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 1111 (delta 396), reused 399 (delta 346), pack-reused 631
Receiving objects: 100% (1111/1111), 741.26 KiB | 1.42 MiB/s, done.
Resolving deltas: 100% (694/694), done.
Submodule path 'module/translation-server': checked out '03290315ad76a06bcb5a993047172a0f90815175'
Submodule 'modules/translate' (https://github.com/zotero/translate.git) registered for path 'module/translation-server/modules/translate'
Submodule 'modules/translators' (https://github.com/zotero/translators) registered for path 'module/translation-server/modules/translators'
Submodule 'modules/utilities' (https://github.com/zotero/utilities.git) registered for path 'module/translation-server/modules/utilities'
Submodule 'modules/zotero-schema' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/zotero-schema'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate'...
remote: Enumerating objects: 260, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 260 (delta 47), reused 38 (delta 32), pack-reused 192
Receiving objects: 100% (260/260), 172.70 KiB | 309.00 KiB/s, done.
Resolving deltas: 100% (140/140), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translators'...
remote: Enumerating objects: 20716, done.
remote: Counting objects: 100% (2162/2162), done.
remote: Compressing objects: 100% (253/253), done.
remote: Total 20716 (delta 1974), reused 2005 (delta 1909), pack-reused 18554
Receiving objects: 100% (20716/20716), 15.85 MiB | 3.87 MiB/s, done.
Resolving deltas: 100% (12457/12457), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/utilities'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 253 (delta 65), reused 73 (delta 50), pack-reused 147
Receiving objects: 100% (253/253), 378.73 KiB | 3.26 MiB/s, done.
Resolving deltas: 100% (126/126), done.
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/zotero-schema'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 2.38 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/translate': checked out '6a9270c992e39998389267810ec21b8cd735730e'
Submodule 'modules/utilities' (https://github.com/zotero/utilities.git) registered for path 'module/translation-server/modules/translate/modules/utilities'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate/modules/utilities'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 253 (delta 65), reused 73 (delta 50), pack-reused 147
Receiving objects: 100% (253/253), 378.73 KiB | 392.00 KiB/s, done.
Resolving deltas: 100% (126/126), done.
Submodule path 'module/translation-server/modules/translate/modules/utilities': checked out 'c173fe4e73f908da917fe7a5dab05ae94d423d6d'
Submodule 'resource/schema/global' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/translate/modules/utilities/resource/schema/global'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/translate/modules/utilities/resource/schema/global'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 3.04 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/translate/modules/utilities/resource/schema/global': checked out '634ba4f99bfd06f4b5b8c88879ff65e2dfd410b3'
Submodule path 'module/translation-server/modules/translators': checked out '8c9da9b034a851c2d22e15aa3c31206d1f2b0f06'
Submodule path 'module/translation-server/modules/utilities': checked out '3143d5518d0044152bdca2b11e5ba2de92b5101f'
Submodule 'resource/schema/global' (https://github.com/zotero/zotero-schema.git) registered for path 'module/translation-server/modules/utilities/resource/schema/global'
Cloning into '/c/Users/user/zotra-cli/module/translation-server/modules/utilities/resource/schema/global'...
remote: Enumerating objects: 181, done.
remote: Counting objects: 100% (119/119), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 181 (delta 44), reused 114 (delta 41), pack-reused 62
Receiving objects: 100% (181/181), 197.30 KiB | 3.46 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Submodule path 'module/translation-server/modules/utilities/resource/schema/global': checked out '634ba4f99bfd06f4b5b8c88879ff65e2dfd410b3'
Submodule path 'module/translation-server/modules/zotero-schema': checked out 'c9f6c78a3d8199de62496c8dc7c188e74ac22341'


C:\Users\user>cd zotra-cli

C:\Users\user\zotra-cli>npm install -g .

up to date in 885ms

C:\Users\user\zotra-cli>
```

**Comment by mpedramfar** [comment]
What if you install it without the `-g` flag? If you use the `-g` flag, you might need to update the `NODE_PATH` variable. (see [this link](https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows))

**Comment by Ypot** [comment]
Adding NODE_PATH variable didn't work...
`
npm install .`
Did work!
THANKS!
